CREATE DATABASE IF NOT EXISTS xtb_pro DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE xtb_pro;

CREATE TABLE IF NOT EXISTS admin_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL,
  mobile VARCHAR(20) DEFAULT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'admin',
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role VARCHAR(20) NOT NULL,
  nickname VARCHAR(50) DEFAULT NULL,
  avatar VARCHAR(255) DEFAULT NULL,
  mobile VARCHAR(20) DEFAULT NULL,
  openid VARCHAR(100) DEFAULT NULL,
  unionid VARCHAR(100) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_app_user_role (role),
  KEY idx_app_user_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_profile (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  real_name VARCHAR(50) NOT NULL,
  school_name VARCHAR(100) DEFAULT NULL,
  major_name VARCHAR(100) DEFAULT NULL,
  grade_name VARCHAR(30) DEFAULT NULL,
  invite_code VARCHAR(30) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_agent_user_id (user_id),
  KEY idx_agent_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS campaign (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  cover VARCHAR(255) DEFAULT NULL,
  description TEXT,
  form_config JSON DEFAULT NULL,
  reward_desc VARCHAR(255) DEFAULT NULL,
  start_time DATETIME DEFAULT NULL,
  end_time DATETIME DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_campaign_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS campaign_share (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  campaign_id BIGINT NOT NULL,
  agent_user_id BIGINT NOT NULL,
  share_code VARCHAR(50) NOT NULL,
  share_url VARCHAR(255) DEFAULT NULL,
  pv INT NOT NULL DEFAULT 0,
  uv INT NOT NULL DEFAULT 0,
  lead_count INT NOT NULL DEFAULT 0,
  order_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_share_code (share_code),
  KEY idx_campaign_share_campaign (campaign_id),
  KEY idx_campaign_share_agent (agent_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lead (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  campaign_id BIGINT NOT NULL,
  agent_user_id BIGINT DEFAULT NULL,
  student_user_id BIGINT DEFAULT NULL,
  name VARCHAR(50) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  school_name VARCHAR(100) DEFAULT NULL,
  major_name VARCHAR(100) DEFAULT NULL,
  grade_name VARCHAR(30) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_lead_campaign (campaign_id),
  KEY idx_lead_agent (agent_user_id),
  KEY idx_lead_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS product (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  campaign_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  original_price DECIMAL(10, 2) DEFAULT NULL,
  cover VARCHAR(255) DEFAULT NULL,
  description TEXT,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_product_campaign (campaign_id),
  KEY idx_product_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(50) NOT NULL,
  product_id BIGINT NOT NULL,
  campaign_id BIGINT DEFAULT NULL,
  agent_user_id BIGINT DEFAULT NULL,
  student_user_id BIGINT DEFAULT NULL,
  student_name VARCHAR(50) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  status TINYINT NOT NULL DEFAULT 0,
  pay_time DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_order_no (order_no),
  KEY idx_orders_product (product_id),
  KEY idx_orders_campaign (campaign_id),
  KEY idx_orders_agent (agent_user_id),
  KEY idx_orders_student (student_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(50) NOT NULL,
  pay_channel VARCHAR(20) NOT NULL DEFAULT 'wechat',
  transaction_id VARCHAR(100) DEFAULT NULL,
  amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  status TINYINT NOT NULL DEFAULT 0,
  raw_callback TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_payment_order_id (order_id),
  KEY idx_payment_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stats_daily (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stat_date DATE NOT NULL,
  campaign_id BIGINT DEFAULT NULL,
  agent_user_id BIGINT DEFAULT NULL,
  pv INT NOT NULL DEFAULT 0,
  uv INT NOT NULL DEFAULT 0,
  lead_count INT NOT NULL DEFAULT 0,
  order_count INT NOT NULL DEFAULT 0,
  paid_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_stats_daily (stat_date, campaign_id, agent_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  login_type VARCHAR(20) NOT NULL,
  admin_user_id BIGINT DEFAULT NULL,
  app_user_id BIGINT DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  role VARCHAR(30) DEFAULT NULL,
  login_status TINYINT NOT NULL DEFAULT 1,
  ip VARCHAR(64) DEFAULT NULL,
  country_name VARCHAR(100) DEFAULT NULL,
  region_name VARCHAR(100) DEFAULT NULL,
  city_name VARCHAR(100) DEFAULT NULL,
  org_name VARCHAR(150) DEFAULT NULL,
  location_text VARCHAR(255) DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  message VARCHAR(255) DEFAULT NULL,
  login_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_login_log_type (login_type),
  KEY idx_login_log_admin_user (admin_user_id),
  KEY idx_login_log_app_user (app_user_id),
  KEY idx_login_log_login_at (login_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO admin_user (username, password, name, mobile, role, status)
VALUES ('admin', '123456', '系统管理员', '13800000000', 'admin', 1)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;
